import type { Metadata } from "next"
import { Architects_Daughter } from "next/font/google"
import "./globals.css"

const architectsDaughter = Architects_Daughter({
  weight: "400",
  style: "normal",
  variable: "--font-architects-daughter",
  subsets: ["latin"],
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={architectsDaughter.className}>{children}</body>
    </html>
  )
}
